export const DSH_RUNTIME_ENTRY_NAMES = {
  '@deepseek-ai/dsh-sdk-jsonrpc-demo/bin': 'bin',
  '@deepseek-ai/dsh-sdk-jsonrpc-server': 'sdk-jsonrpc-server',
  '@deepseek-ai/dsh-llm-pi-ai': 'llm-pi-ai',
  '@deepseek-ai/dsh-llm-retry': 'llm-retry',
  '@deepseek-ai/dsh-pwsh-local': 'pwsh-local',
  '@deepseek-ai/dsh-pwsh-sandbox': 'pwsh-sandbox',
  '@deepseek-ai/dsh-sandbox-local': 'sandbox-local',
  '@deepseek-ai/dsh-sandbox-policy': 'sandbox-policy',
  '@deepseek-ai/dsh-subprocess-local': 'subprocess-local',
  '@deepseek-ai/dsh-bash-sandbox': 'bash-sandbox',
  '@deepseek-ai/dsh-user-approval': 'user-approval',
  '@deepseek-ai/dsh-agent-spine-demo': 'agent-spine-demo',
  '@deepseek-ai/dsh-attachment-local': 'attachment-local',
  '@deepseek-ai/dsh-fs-local': 'fs-local',
  '@deepseek-ai/dsh-tool-fs': 'tool-fs',
  '@deepseek-ai/dsh-tool-todo': 'tool-todo',
  '@deepseek-ai/dsh-token-meter': 'token-meter',
  '@deepseek-ai/dsh-session-projection': 'session-projection',
  '@deepseek-ai/dsh-compaction-tool-result-pruner': 'compaction-tool-result-pruner',
  '@deepseek-ai/dsh-compaction-basic': 'compaction-basic',
  '@deepseek-ai/dsh-commands': 'commands',
  '@deepseek-ai/dsh-command-compact': 'command-compact',
  '@deepseek-ai/dsh-command-goal': 'command-goal',
  '@deepseek-ai/dsh-goal': 'goal',
  '@deepseek-ai/dsh-goal-round-driver': 'goal-round-driver',
  '@deepseek-ai/dsh-tool-goal': 'tool-goal',
  '@deepseek-ai/dsh-subagent': 'subagent',
  '@deepseek-ai/dsh-subagent-spawn-in-process': 'subagent-spawn-in-process',
  '@deepseek-ai/dsh-subagent-fork-in-process': 'subagent-fork-in-process',
  '@deepseek-ai/dsh-tool-subagent-control': 'tool-subagent-control',
  '@deepseek-ai/dsh-tool-subagent-control/list-agents': 'tool-subagent-list-agents',
  '@deepseek-ai/dsh-tool-subagent': 'tool-subagent',
  '@deepseek-ai/dsh-tool-subagent-report': 'tool-subagent-report',
  '@deepseek-ai/dsh-user-questions': 'user-questions',
  '@deepseek-ai/dsh-plan-mode': 'plan-mode',
  '@deepseek-ai/dsh-session-persistence-jsonl': 'session-persistence-jsonl',
  '@deepseek-ai/dsh-shell-env': 'shell-env',
  '@deepseek-ai/dsh-tool-pwsh': 'tool-pwsh',
  '@cherrystudio/dsh-bridge/plugin': 'cherry-bridge'
} as const

export type DshRuntimeEntrySpecifier = keyof typeof DSH_RUNTIME_ENTRY_NAMES
