/**
 * Generates `src/shared/utils/systemProviderId.ts` from the provider-registry
 * catalog so the SystemProviderId enum can never drift from the shipped set.
 *
 * Source of truth: `packages/provider-registry/data/providers.json`. Every
 * registry provider id becomes a SystemProviderId EXCEPT the agent/CLI-only
 * auth backends in {@link CLI_ONLY_PROVIDER_IDS} (those aren't user-configurable
 * providers in Settings → Providers).
 *
 * Run via `pnpm gen:system-provider-ids`. CI runs it and fails on any diff,
 * mirroring the DB-migrations generate-and-diff guard.
 */

import * as fs from 'fs'
import * as path from 'path'

const ROOT_DIR = path.join(__dirname, '..')
const PROVIDERS_JSON = path.join(ROOT_DIR, 'packages', 'provider-registry', 'data', 'providers.json')
const OUTPUT_FILE = path.join(ROOT_DIR, 'src', 'shared', 'utils', 'systemProviderId.ts')

/**
 * Registry provider ids that are agent/CLI auth backends, NOT user-configurable
 * "system providers" in Settings → Providers — so they are excluded from
 * SystemProviderId. Every entry must exist in the registry (the generator
 * throws otherwise, catching a stale exclude after an upstream rename/removal).
 */
export const CLI_ONLY_PROVIDER_IDS = ['claude-code', 'openai-codex', 'grok-cli']

/** Derive the SystemProviderId set from a raw `providers.json` string, sorted. */
export function extractSystemProviderIds(providersJson: string): string[] {
  const parsed = JSON.parse(providersJson) as { providers: Array<{ id: string }> }
  const registryIds = parsed.providers.map((p) => p.id)
  const registrySet = new Set(registryIds)

  const staleExcludes = CLI_ONLY_PROVIDER_IDS.filter((id) => !registrySet.has(id))
  if (staleExcludes.length > 0) {
    throw new Error(
      `CLI_ONLY_PROVIDER_IDS lists ids absent from the registry: ${staleExcludes.join(', ')}. ` +
        `Update CLI_ONLY_PROVIDER_IDS in scripts/generate-system-provider-ids.ts.`
    )
  }

  const excluded = new Set(CLI_ONLY_PROVIDER_IDS)
  return registryIds.filter((id) => !excluded.has(id)).sort((a, b) => a.localeCompare(b))
}

const isValidIdentifier = (s: string) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s)
const objectKey = (id: string) => (isValidIdentifier(id) ? id : `'${id}'`)

const BANNER = `// AUTO-GENERATED by scripts/generate-system-provider-ids.ts — DO NOT EDIT.
// Regenerate with \`pnpm gen:system-provider-ids\`. Source of truth:
// packages/provider-registry/data/providers.json (every provider id except the
// agent/CLI-only backends in CLI_ONLY_PROVIDER_IDS in that script).`

/** Render the full TypeScript module for the given (sorted) provider ids. */
export function renderSystemProviderIdsFile(ids: string[]): string {
  const enumEntries = ids.map((id) => `  '${id}'`).join(',\n')
  const mapEntries = ids.map((id) => `  ${objectKey(id)}: '${id}'`).join(',\n')

  return `${BANNER}

import * as z from 'zod'

export const SystemProviderIdSchema = z.enum([
${enumEntries}
])

export type SystemProviderId = z.infer<typeof SystemProviderIdSchema>

export const isSystemProviderId = (id: string): id is SystemProviderId => {
  return SystemProviderIdSchema.safeParse(id).success
}

export const SystemProviderIds = {
${mapEntries}
} as const satisfies Record<SystemProviderId, SystemProviderId>
`
}

export function main(): void {
  const providersJson = fs.readFileSync(PROVIDERS_JSON, 'utf8')
  const ids = extractSystemProviderIds(providersJson)
  fs.writeFileSync(OUTPUT_FILE, renderSystemProviderIdsFile(ids))
  console.log(`Generated ${OUTPUT_FILE} with ${ids.length} provider ids.`)
}

if (require.main === module) {
  main()
}
